In [13]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x=np.array(5)
print(x)

5


In [4]:
y=x*2
print(y)

10


In [17]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1,arr2)

[1 2 3] [[1 2 3 4]
 [5 6 7 8]]


<h3>array shape, dtype, dimension</h3>

In [12]:
print(arr1.shape,arr1.dtype,arr1.ndim)
print(arr2.shape,arr2.dtype,arr2.ndim)

(4,) int64 1
(2, 4) int64 2


<h3>vector dot product</h3>

In [19]:
vec1=np.array([1,2,3])
vec2=np.array([4,5,6])
print(np.dot(vec1,vec2))

32


<h3>Vector normalization (L2)</h3>
<p>Normalization gives the unitt vector. Helpful to find cosine similarities between vectors sine they are unit vecors, only the angle contribute to the similarity not how big it is</p>

In [20]:
vec3=np.array([1,2,3])
norm=np.linalg.norm(vec3)
normalized_vec=vec3/norm
print(vec3,norm,normalized_vec)

[1 2 3] 3.7416573867739413 [0.26726124 0.53452248 0.80178373]


<h3>Cosine similarity</h3>
<p>Cosine similarity gives the angle between vectors.the closer to 1, the more similar they are.</p>
cos(theta)=vec dot products/vector size multiples

In [23]:
vec4=np.array([1,2,3])
vec5=np.array([4,5,6])
dot_product=np.dot(vec4,vec5)
norm4=np.linalg.norm(vec4)
norm5=np.linalg.norm(vec5)
cosine=dot_product/(cosine)
print(cosine)

0.42640143271122083


<h2>Matrices</h2>

In [24]:
matr1=np.array([[1,2],[3,4]])
print(matr1.shape,matr1.dtype)

(2, 2) int64


<h3>Matrix multiplication & Dot product</h3>

In [27]:
mat2=np.array([[1,2],[3,4]])
mat3=np.array([[5,6],[7,8]])
mult=np.matmul(mat2,mat3)
dot=mat2*mat3
print(mult)
print(dot)

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


<h3>Identity matrix</h3>

In [28]:
I=np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<h3>Diagonal matrix</h3>

In [29]:
D=np.diag([1,2,3,4])
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


<h3>Inverse matrices</h3>
<p>Ax=b -> x=A(inv)b</p>
<p><b>A must be square and its determintent should not be 0 to have an inverse</b></p>

In [30]:
A=np.array([[1,2],[3,4]])
A_inv=np.linalg.inv(A)
b=np.array([5,11])
x=np.dot(A_inv,b)
print(b)

[ 5 11]
